import Head from 'next/head'
import Layout from '../components/Layout.js'
import homeStyles from '../styles/Home.module.scss'
import Image from 'next/image'

export default function Home() {
  return (
    
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout home>
       </Layout>
      <main>
        
        <h1></h1>
      </main>

      <footer>

      </footer>
    </div>
  )
}
