import Head from 'next/head'
import Layout from '../components/Layout.js'
import homeStyles from '../styles/Home.module.scss'
import Lead from '../components/Lead';
import Image from 'next/image'

export default function Home() {
  return (
    
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout home>
      <Lead home />
      </Layout>


      <footer>

      </footer>
    </div>
  )
}
