import Head from 'next/head'
import Layout from '../components/Layout.js'
import homeStyles from '../styles/Home.module.scss'
import Lead from '../components/Lead';
import Image from 'next/image'

export default function Home() {
  return (
    
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="crossorigin="anonymous"></script>
        <script type="text/javascript" src="../static/js/common.js"></script>
      </Head>
      <Layout home>
      <Lead home />      
      
      <section>
        <div className="box_background__black">
          <span>OUR SERVICE</span>
        </div>
        <div className="box_background__whtite">
         <ul>
           <li>
             <dl>
               <dt>WEB CREATION</dt>
               <dd>戦略、設計、実装までワンストップでチームでWEBサイトの構築を対応します。ランディングページ、コーポレートサイト等、小規模から大規模まで幅広く対応します。</dd>
              </dl>
           </li>
           <li>
             <dl>
               <dt>SYSTEM INTEGRATION</dt>
               <dd>Wordpressカスタマイズ、ECサイト、受付サイト、管理システム等のシステム開発をしています。PHP・Javascriptを得意としています。</dd>
              </dl>
           </li>
           <li>
             <dl>
               <dt>WEB OPERATION</dt>
               <dd>WEBサイトの運用として、コンテンツ更新、アクセス解析、効果計測、改善施策の立案・実施を対応します。ITパートナーとしてビジネス理解を通して、お客様のWEBを管理をします。</dd>
              </dl>
           </li>                      
         </ul>
        </div>
      </section>
      </Layout>


      <footer>

      </footer>
    </div>
  )
}
